# Generated by Django 5.2.7 on 2025-10-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('ID_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=20)),
                ('stock', models.PositiveIntegerField()),
                ('categoria', models.CharField(max_length=50)),
                ('unidad_medida', models.CharField(max_length=50, verbose_name='Unidad de Medida (Ej: kg)')),
            ],
        ),
    ]
